# Generated by Django 3.0.4 on 2020-04-14 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('matrikel_number', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=11)),
                ('postal_code', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
