# Generated by Django 3.0.4 on 2020-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentArchives',
            fields=[
                ('matrikel_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=11)),
                ('postal_code', models.CharField(max_length=6)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
