# Generated by Django 3.0.4 on 2020-03-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentarchives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentarchives',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentarchives',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
