# Generated by Django 3.0.4 on 2020-05-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('primary_image_id', models.IntegerField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Products')),
            ],
            options={
                'ordering': ['image_id'],
            },
        ),
    ]
