# Generated by Django 3.0.4 on 2020-03-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200304_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('primary_image_id', models.IntegerField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Products')),
            ],
        ),
    ]
